### ISSUE TITLE
Mod doesn't auto wb after someone has joined for the first time

### ISSUE THREAD

**Issue by BeefyAndTheDucks** [tolek-tpr/ModForLazyPeople#11]
Someone joined Synergy for the first time and the bot said welcome but afterwards the bot would never say wb again.

**Comment by tolek-tpr** [comment]
Yea, I've noticed that too but thought that it was just me. Try relogging. Will try to fix this in the next update, however that might take a bit more time than usual, because of a hotkey rewrite.
